-- liquibase formatted sql

-- changeset kalsara Magamage:classifier-script-v7-changeset1
CREATE TABLE stop_words (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    stop_word TEXT NOT NULL,
    CONSTRAINT stop_words_pkey PRIMARY KEY (id),
    CONSTRAINT stop_words_unique UNIQUE (stop_word)
);