-- liquibase formatted sql

-- changeset kalsara Magamage:classifier-script-v1-changeset1
CREATE TYPE user_status AS ENUM ('active','deleted');

-- changeset kalsara Magamage:classifier-script-v1-changeset2
CREATE TABLE public."user" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(50) NOT NULL,
    password_hash VARCHAR(60),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    id_code VARCHAR(50) NOT NULL,
    display_name VARCHAR(50),
    status user_status,
    csa_title VARCHAR,
    csa_email VARCHAR,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE public."authority" (
    name VARCHAR(50) PRIMARY KEY
);

CREATE TABLE public."user_authority" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id VARCHAR(50) NOT NULL,
    authority_name VARCHAR[] NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_authority_pkey PRIMARY KEY (id)
);