-- liquibase formatted sql

-- changeset kalsara Magamage:classifier-script-v3-changeset1
CREATE TYPE platform AS ENUM ('JIRA', 'OUTLOOK');

-- changeset kalsara Magamage:classifier-script-v3-changeset2
CREATE TABLE public."integration_status" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    platform platform,
    is_connect BOOLEAN NOT NULL DEFAULT FALSE,
    subscription_id VARCHAR(50) DEFAULT NULL,
    token TEXT DEFAULT NULL,
    CONSTRAINT integration_status_pkey PRIMARY KEY (id)
);

-- changeset kalsara Magamage:classifier-script-v3-changeset3
INSERT INTO public."integration_status" (platform, is_connect, subscription_id, token)
VALUES
    ('JIRA', FALSE, NULL, NULL),
    ('OUTLOOK', FALSE, NULL, NULL);

-- changeset kalsara Magamage:classifier-script-v3-changeset4
CREATE TABLE public."input" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inference_time_stamp TIMESTAMP WITH TIME ZONE,
    input_id TEXT NOT NULL,
    inference_text TEXT DEFAULT NULL,
    predicted_labels JSONB,
    corrected_labels JSONB,
    is_corrected BOOLEAN NOT NULL DEFAULT FALSE,
    average_predicted_classes_probability INT,
    average_corrected_classes_probability INT,
    primary_folder_id TEXT DEFAULT NULL,
    platform platform,
    CONSTRAINT input_pkey PRIMARY KEY (id),
    CONSTRAINT input_id_unique UNIQUE (input_id)
);