-- liquibase formatted sql

-- changeset kalsara Magamage:classifier-script-v4-changeset1
CREATE TABLE public.configuration (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    key VARCHAR(128),
    value VARCHAR(128),
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT configuration_pkey PRIMARY KEY (id)
);

-- changeset kalsara Magamage:classifier-script-v4-changeset2
INSERT INTO public.configuration (key, value)
VALUES ('session_length', '120');
