-- liquibase formatted sql

-- changeset kalsara Magamage:classifier-ddl-script-v1-changeset1
CREATE TYPE platform AS ENUM ('JIRA', 'OUTLOOK', 'PINAL');

-- changeset kalsara Magamage:classifier-ddl-script-v1-changeset2
CREATE TABLE public."integration_status" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    platform platform,
    is_connect BOOLEAN NOT NULL DEFAULT FALSE,
    subscription_id VARCHAR(50) DEFAULT NULL,
    token TEXT DEFAULT NULL,
    CONSTRAINT integration_status_pkey PRIMARY KEY (id)
);

-- changeset kalsara Magamage:classifier-ddl-script-v1-changeset3
INSERT INTO public."integration_status" (platform, is_connect, subscription_id, token)
VALUES
    ('JIRA', FALSE, NULL, NULL),
    ('OUTLOOK', FALSE, NULL, NULL),
    ('PINAL', FALSE, NULL, NULL);