export enum INTEGRATION_MODALS {
  INTEGRATION_SUCCESS = 'INTEGRATION_SUCCESS',
  INTEGRATION_ERROR = 'INTEGRATION_ERROR',
  DISCONNECT_CONFIRMATION = 'DISCONNECT_CONFIRMATION',
  CONNECT_CONFIRMATION = 'CONNECT_CONFIRMATION',
  DISCONNECT_ERROR = 'DISCONNECT_ERROR',
  NULL = 'NULL',
}

export enum INTEGRATION_OPERATIONS {
  ENABLE = 'enable',
  DISABLE = 'disable',
}
